apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    # name: in-cluster
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  source:
    path: ../apps
    repoURL: 'https://github.com/cyberslot/argo-cd-app-of-apps-demo'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true