apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # path: argocd-apps/nginx-gateway-api/helm/nginx-gateway-fabric
    repoURL: https://ghcr.io/nginxinc/charts/nginx-gateway-fabric
    chart: nginx-gateway-fabric
    targetRevision: '0.0.0-edge'
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  destination:
    namespace: nginx-gateway
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true