apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: argocd-apps/nginx-gateway-api/helm/nginx-gateway-fabric
    repoURL: https://github.com/cyberslot/argo-cd-app-of-apps-demo.git
    # chart: nginx-gateway-fabric
    targetRevision: HEAD
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  destination:
    namespace: nginx-gateway
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true