apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bitnami-labs/sealed-secrets/tree/main/helm
    chart: sealed-secrets
    targetRevision: '0.24.2'
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  destination:
    namespace: sealed-secrets
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true